name: Simple CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Build Application
        run: ./gradlew bootJar

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "Built version: $VERSION" 
          echo "Ready for deployment!"